import { LegalDoc } from "@/components/LegalDoc";
import { OPERATOR, TERMS_VERSION } from "@/lib/legal";

export const metadata = { title: "Concierge AI — Attracco" };

export default function AiNotice() {
  return (
    <LegalDoc
      version={TERMS_VERSION}
      it={
        <>
          <h1>Come funziona il concierge AI</h1>
          <p>
            Il concierge di Attracco è un sistema di intelligenza artificiale. Quando scrivi in chat interagisci con un software, non con una
            persona. Lo indichiamo in modo chiaro, come previsto dall&apos;art. 50 del Regolamento (UE) 2024/1689 (AI Act). [Verificare la
            disciplina nazionale di cui alla L. 132/2025 e l&apos;eventuale incidenza del pacchetto &laquo;Digital Omnibus&raquo; sulle tempistiche.]
          </p>
          <h2>Cosa fa</h2>
          <p>
            Ti aiuta a scegliere tra i servizi del catalogo Attracco in Puglia, ne riassume le caratteristiche e prepara un preventivo. Il prezzo è
            calcolato dal nostro sistema in base al listino del Fornitore, non generato dall&apos;AI.
          </p>
          <h2>Cosa non fa</h2>
          <p>
            Non conclude contratti, non accetta pagamenti, non conferma disponibilità e non prende decisioni sul tuo conto: la prenotazione avviene
            solo tramite il modulo e la conferma spetta al Fornitore. Non fornisce consulenza legale, medica o fiscale.
          </p>
          <h2>Limiti</h2>
          <p>
            Le risposte possono contenere errori o imprecisioni. Fanno fede solo le informazioni della scheda servizio e del riepilogo di
            prenotazione. Se noti una risposta errata o inappropriata, segnalala a {OPERATOR.email}.
          </p>
          <h2>Tecnologia e dati</h2>
          <p>
            Il concierge usa un modello linguistico fornito da Anthropic (famiglia Claude) tramite API. I messaggi sono inviati al fornitore per
            generare la risposta e non sono salvati da Attracco. [Verificare nei termini commerciali del fornitore: assenza di uso dei dati API per
            l&apos;addestramento, periodo di conservazione, disponibilità di elaborazione in UE.] Non inserire in chat dati personali o sanitari:
            il modulo di prenotazione raccoglie quanto necessario con le relative informative.
          </p>
          <h2>Supervisione umana</h2>
          <p>
            Il catalogo, i prezzi e le istruzioni del concierge sono definiti e controllati dal personale di Attracco; ogni prenotazione è
            verificata e confermata da una persona.
          </p>
        </>
      }
      en={
        <>
          <h1>How the AI concierge works</h1>
          <p>
            Attracco&apos;s concierge is an artificial intelligence system. When you chat, you are interacting with software, not a person. We make
            this clear in line with Article 50 of Regulation (EU) 2024/1689 (AI Act).
          </p>
          <h2>What it does</h2>
          <p>
            It helps you choose among Attracco&apos;s services in Puglia, summarises them and prepares a quote. Prices are computed by our system
            from the Provider&apos;s price list, not generated by the AI.
          </p>
          <h2>What it doesn&apos;t do</h2>
          <p>
            It does not conclude contracts, take payments, confirm availability or make decisions about you: bookings happen only through the form,
            and the Provider confirms them. It gives no legal, medical or tax advice.
          </p>
          <h2>Limitations</h2>
          <p>
            Answers may contain mistakes. Only the service page and booking summary are binding. Please report wrong or inappropriate answers to{" "}
            {OPERATOR.email}.
          </p>
          <h2>Technology and data</h2>
          <p>
            The concierge uses a language model provided by Anthropic (Claude family) via API. Messages are sent to the provider to generate
            replies and are not stored by Attracco. Please don&apos;t share personal or health data in the chat.
          </p>
          <h2>Human oversight</h2>
          <p>
            The catalog, prices and concierge instructions are set and supervised by Attracco staff; every booking is reviewed and confirmed by a
            person.
          </p>
        </>
      }
    />
  );
}
